n = input("Digite algo:")
print('O que você escreveu é do tipo?', type(n))
print('O que você escreveu é numerico?', n.isnumeric())
print('O que você escreveu é alfabetico?', n.isalpha())
print('O que você escreveu é letras minusculas?', n.islower())
print('O que você escreveu é maiusculo?', n.isupper())
print('O que você escreveu é imprimivel?', n.isprintable())
print('O que você escreveu é um espaço?', n.isspace())
print('O que você escreeu é um digito?', n.isdigit())
print('Isso é tudo! Obrigada pela participação')
